package com.ourapp.counterapp;

import static com.codename1.ui.CN.*;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class Main extends Lifecycle {
    @Override
    public void runApp() {

        //creates a new page
        Form hi = new Form("Hi World", BoxLayout.y());
        //creates a new button
        Button helloButton = new Button("Hello World");
        //adds the button
        hi.add(helloButton);
        //if button is pressed runs the test page method
        helloButton.addActionListener(e -> testPage());
        //adds a menu item
        hi.getToolbar().addMaterialCommandToSideMenu("1st menu item test",
        FontImage.MATERIAL_CHECK, 4, e -> hello());
        //adds a 2nd menu item
        hi.getToolbar().addMaterialCommandToSideMenu("2nd menu item test",
                FontImage.MATERIAL_CHECK, 4, e -> hello());
        //displays the page created earlier
        hi.show();
    }
    //creates a new page and runs the page
    public void testPage(){
        Form two = new Form("testpage",BoxLayout.y());
        two.show();
    }

    private void hello() {
        Dialog.show("Hello Codename One", "Welcome to Codename One", "OK", null);
    }

}
